project:
  type: book
  output-dir: docs
  preview: 
    port: 4200
    browser: true

book:
  title: "Empirical Research in Economics"
  author: "Mohammed Seid Hussen"
  date: today
  cover-image: cover.png
  repo-url: https://github.com/mohammed-seid/economics_research.git
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, facebook, linkedin]
  open-graph:
    image: https://github.com/mohammed-seid/economics_research/blob/main/image/wide-cover.png
  twitter-card:
    image: https://github.com/mohammed-seid/economics_research/blob/main/image/wide-cover.png
  site-url: https://mohammed-seid.github.io/economics_research/
  chapters:
    - part: index.qmd
      chapters:
      - p0c1-intro.qmd
    - part: p1-fundamentals.qmd
      chapters:
        - p1c1-r-studio.qmd
    - part: p2-data-acquisition.qmd
      chapters:
        - p2c1-import-datasets.qmd
        - p2c2-data-cleaning.qmd
    - part: p4-developing-insights.qmd
      chapters:
        - p4c1-summary-statistics.qmd
        - p4c2-regression.qmd
        - p4c3-plotting.qmd
        - p4exercises.qmd
    - part: p5-reporting.qmd
      chapters: 
        - p5c1-spreadsheets.qmd
        - p5c2-r-markdown.qmd
        - p5c3-r-shiny.qmd
        - p5exercises.qmd
    - references.qmd

bibliography: references.bib

comments:
  hypothesis: false

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


